apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-app
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/pilotgab/bankapp-blue-green-deployment.git"
        revision: main
        files:
          - path: "appset/monitoring/*.yaml"
  template:
    metadata:
      name: "{{application}}"
    spec:
      project: "default"
      source:
        chart: "{{chart.name}}"
        repoURL: "{{chart.repoURL}}"
        targetRevision: "{{chart.targetRevision}}"
        helm:
          releaseName: "{{chart.releaseName}}"
          values: |-
            {{chart.values }}
      destination:
        namespace: "{{clusterConfig.namespace }}"
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - "ServerSideApply=true"
          - CreateNamespace=true
        retry:
          limit: 1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
