application: kube-prometheus-stack
clusterConfig:
  namespace: monitoring
chart:
  name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  repoURL: https://prometheus-community.github.io/helm-charts
  targetRevision: 68.1.1
  values: |
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}

    grafana:
      sidecar:
        datasources:
          defaultDatasourceEnabled: true
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki-loki-distributed-query-frontend.monitoring:3100
