application: kube-prometheus-stack
clusterConfig:
  namespace: monitoring
chart:
  name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  repoURL: https://prometheus-community.github.io/helm-charts
  targetRevision: 56.21.4
values: |
  alertmanager:
    enabled: true

  server:
    persistentVolume:
      enabled: true
      size: 50Gi
      storageClass: gp2
    extraArgs:
      - '--storage.tsdb.retention.time=7d'

  serviceAccount:
    create: true
    name: prometheus-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::345594590281:role/prom-role
